services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # 1. Aktifkan Mode KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      
      # 2. Listeners & Protocols
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      # 3. Cluster ID (Wajib Unik untuk KRaft)
      # Anda bisa menggunakan string random apa saja
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      
      # 4. Fitur Lainnya
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:latest
    container_name: redis
  
  mwallet-eureka:
    build:
      context: ./mwallet-eureka
    container_name: mwallet-eureka
    ports:
      # Mengubah port luar ke 9761
      - "9761:8761" 

  mwallet-gateway:
    build:
      context: ./mwallet-gateway
    container_name: mwallet-gateway
    ports:
      # Mengubah port luar ke 9080
      - "9080:8080"
    env_file:
      - .env
    depends_on:
      - mwallet-eureka

  mwallet-user:
    build:
      context: ./mwallet-user
    container_name: mwallet-user
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - kafka
      - redis
      - mwallet-eureka

  mwallet-transaction:
    build:
      context: ./mwallet-transaction
    container_name: mwallet-transaction
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - kafka
      - redis
      - mwallet-eureka

networks:
  default:
    name: microservices-network