spring:
  application:
    name: MWALLET-USER

  datasource:
    url: jdbc:postgresql://localhost:5432/mwallet
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
